# Generated by Django 6.0.4 on 2026-04-24 09:38

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('under_review', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('assigned', 'Место назначено'), ('checked_in', 'Заселён')], default='draft', max_length=20, verbose_name='Статус')),
                ('ege_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма баллов ЕГЭ')),
                ('diploma_type', models.CharField(choices=[('regular', 'Обычный'), ('red', 'С отличием'), ('sp_red', 'СПО с отличием')], default='regular', max_length=50, verbose_name='Тип аттестата/диплома')),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расстояние от места жительства (км)')),
                ('has_priority_benefit', models.BooleanField(default=False, verbose_name='Льготная категория (ФЗ №273)')),
                ('rating_score', models.FloatField(default=0.0, verbose_name='Рейтинговый балл')),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в очереди')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-rating_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='PDF-копия договора')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписан')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('medical_086', 'Справка 086/у'), ('fluoro', 'Флюорография'), ('vaccination', 'Прививочный сертификат'), ('benefit_proof', 'Подтверждение льготы'), ('achievement', 'Достижения/Олимпиады')], max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=applications.models.application_doc_path, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен администратором')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к проверке')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
