# Generated by Django 6.0.4 on 2026-04-24 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('dorms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Абитуриент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='applications.application', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorms.room', verbose_name='Комната'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='Заявка'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('application', 'doc_type')},
        ),
    ]
