# Generated by Django 6.0.4 on 2026-04-24 18:25

import applications.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('dorms', '0002_alter_dormitory_options_alter_room_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-rating_score', 'created_at'], 'verbose_name': 'Заявка на заселение', 'verbose_name_plural': 'Заявки на заселение'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Договор найма', 'verbose_name_plural': 'Договоры найма'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['doc_type', 'uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_signed',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='room',
        ),
        migrations.AddField(
            model_name='application',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='dorms.room', verbose_name='Назначенная комната'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Инвалид I или II группы'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_orphan',
            field=models.BooleanField(default=False, verbose_name='Ребёнок-сирота'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(default='TEMP001', max_length=50, unique=True, verbose_name='Номер договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='is_signed_by_student',
            field=models.BooleanField(default=False, verbose_name='Подписан студентом'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_signed_by_university',
            field=models.BooleanField(default=False, verbose_name='Подписан университетом'),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ежемесячная плата (руб.)'),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='diploma_type',
            field=models.CharField(choices=[('regular', 'Обычный аттестат/диплом'), ('red_high_school', 'Аттестат с отличием (школа)'), ('red_college', 'Диплом с отличием (СПО)')], default='regular', max_length=20, verbose_name='Тип аттестата/диплома'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ege_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Сумма баллов ЕГЭ'),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_priority_benefit',
            field=models.BooleanField(default=False, verbose_name='Льготная категория (сироты, инвалиды и др.)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Рейтинговый балл'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена на рассмотрение'), ('under_review', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('assigned', 'Место назначено'), ('checked_in', 'Заселён'), ('checked_out', 'Выселен')], default='draft', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Студент/Абитуриент'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport_main', 'Паспорт (разворот с фото)'), ('passport_registration', 'Паспорт (прописка)'), ('medical_086', 'Медицинская справка 086/у'), ('fluoro', 'Флюорография'), ('vaccination', 'Прививочный сертификат'), ('hiv_certificate', 'Справка об отсутствии ВИЧ (для иностранцев)'), ('benefit_proof', 'Подтверждение льготы'), ('achievement', 'Достижения (олимпиады, грамоты)'), ('parent_passport', 'Паспорт законного представителя'), ('parent_consent', 'Согласие законного представителя')], max_length=30, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=applications.models.application_doc_path, verbose_name='Файл документа'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'created_at')},
        ),
    ]
