# Generated by Django 6.0.4 on 2026-04-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название корпуса')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='Общая вместимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежития',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Вместимость (чел.)')),
                ('current_occupancy', models.PositiveIntegerField(default=0, verbose_name='Заселено')),
                ('status', models.CharField(choices=[('available', 'Свободна'), ('occupied', 'Занята'), ('under_repair', 'На ремонте'), ('reserved', 'Зарезервирована')], default='available', max_length=20, verbose_name='Статус')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dorms.dormitory', verbose_name='Общежитие')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'unique_together': {('dormitory', 'number')},
            },
        ),
    ]
