# Generated by Django 6.0.4 on 2026-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormitory',
            options={'ordering': ['name'], 'verbose_name': 'Общежитие', 'verbose_name_plural': 'Общежития'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['dormitory', 'floor', 'number'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='total_capacity',
            field=models.PositiveIntegerField(verbose_name='Общая вместимость (чел.)'),
        ),
    ]
